[build]
  publish = "dist/"

  command = "npm run generate"

  functions = "scripts"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[plugins]]
  package = "./plugins/netlify-plugin-algolia-index"
    [plugins.inputs]
      exclude = ['/admin']

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true
  