[build]
  publish = "dist"
  command = "npm run generate"
  functions = "scripts"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[plugins]]
  package = "netlify-plugin-algolia-index"
    [plugins.inputs]
      exclude = ['/admin', '/200.html', '/archive', '/blog/tag', '/blog/category']

[[plugins]]
  package = "@netlify/plugin-sitemap"
    [plugins.inputs]
      buildDir = "dist"

[[plugins]]
  package = "netlify-plugin-no-more-404"
    [plugins.inputs]
      on404 = "warn" 
      cacheKey = "vonage-dev-blog"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true
