[build]
  publish = "dist"
  command = "npm run generate"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/Vonage-footer-logo.svg"
  to = "/.netlify/functions/image.jpg"
  status = 200
  force = true
