backend:
  name: git-gateway
  branch: main

i18n:
  structure: multiple_folders
  locales: [en, it, cn]
  default_locale: en

publish_mode: editorial_workflow

media_folder: '/static/content/images/'
public_folder: '/content/images/'

collections:
  - name: blog
    i18n: true
    label: 'Blog Post'
    format: frontmatter
    folder: '/content/blog'
    media_folder: '/static/content/blog/{{slug}}/'
    public_folder: '/content/blog/{{slug}}/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
        hint: "Post title and meta title. Soft limit 60 characters, hard limit 70 characters."
        i18n: true
      - label: Description
        name: description
        widget: string
        hint: "Post meta description. Soft limit 120 characters, hard limit 160 characters."
        i18n: true
      - label: 'Featured Image'
        name: thumbnail
        widget: image
        allow_multiple: false
        hint: "Featured image that appears at the top of the post."
      - label: Author
        name: author
        widget: relation
        collection: pages
        file: authors
        searchFields: ["authors.*.username", "authors.*.name", "authors.*.twitter"]
        valueField: "authors.*.username"
        displayFields: ["authors.*.name"]
        hint: "Search for the post author. If not found, go add them at *Pages* » *Authors* first."
      - label: Published
        name: published
        widget: boolean
        default: true
        hint: "Always true, unless you want to create an UNPUBLISHED post. Setting to false after publish will not remove it from Algolia."
      - label: 'Published At'
        name: published_at
        widget: datetime
        hint: "Date and time post is published."
      - label: 'Updated At'
        name: updated_at
        widget: datetime
        required: false
        hint: "Date and time post was last updated."
      - label: Category
        name: category
        widget: relation
        collection: pages
        file: categories
        searchFields: ["categories.*.name", "categories.*.slug", "categories.*.plural"]
        valueField: "categories.*.slug"
        displayFields: ["categories.*.plural"]
        hint: "Search for the post category. Pre-approved categories, but can be edited at *Pages* » *Categories*."
      - label: Tags
        name: tags
        widget: list
        hint: "Please include languages, platforms, products. i.e. nodejs, aws, messages-api"
      - label: Spotlight
        name: spotlight
        widget: boolean
        default: false
        required: false
        hint: "Whether the post is part of the Spotlight programme."
      - label: Body
        name: body
        widget: markdown
        i18n: true
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - label: 'Authors'
        name: authors
        file: 'content/authors.json'
        fields:
          - label: Authors
            name: authors
            identifier_field: username
            widget: list
            fields:
              - label: Username
                name: username
                widget: string
                hint: "Author username. i.e. lukeoliff (if copying from Wordpress, use the slug from your profile URL)"
              - label: Name
                name: name
                widget: string
                hint: "Visible full name. i.e. Luke Oliff"
              - label: 'User Image'
                name: 'image_url'
                widget: 'image'
                allow_multiple: false
                hint: "Profile picture for authors list and author profile page"
              - label: 'Twitter'
                name: twitter
                widget: string
                hint: "Your twitter username WITHOUT the @"
              - label: Bio
                name: bio
                widget: text
                required: false
                hint: "About you, your bio."
              - label: 'Job Title'
                name: title
                widget: string
                required: false
                hint: "Job title"
              - label: Email
                name: email
                widget: string
                required: false
                hint: "Email address (not required, but also not public)"
              - label: Team Member
                name: team
                widget: boolean
                default: false
                required: false
                hint: "Is this user part of the Vonage team?"
              - label: Team Alumni (former member)
                name: alumni
                widget: boolean
                default: false
                required: false
                hint: "Was this user part of the Vonage or Nexmo team in the past?"
              - label: Spotlight
                name: spotlight
                widget: boolean
                default: false
                required: false
                hint: "Is this user part of the Spotlight programme?"
              - label: Noteworthy
                name: noteworthy
                widget: boolean
                default: false
                required: false
                hint: "If not Spotlight or team, is this author otherwise noteworthy?"
              - label: 'Website Url'
                name: website_url
                widget: string
                required: false
                hint: "Public URL, but will default to your author profile URL if not supplied (without UTMs we add those)"
              - label: 'Facebook Url'
                name: facebook_url
                widget: string
                required: false
                hint: "Public profile URL (without UTMs we add those)"
              - label: 'GitHub Url'
                name: github_url
                widget: string
                required: false
                hint: "Public profile URL (without UTMs we add those)"
              - label: 'StackOverflow Url'
                name: stackoverflow_url
                widget: string
                required: false
                hint: "Public profile URL (without UTMs we add those)"
              - label: 'LinkedIn Url'
                name: linkedin_url
                widget: string
                required: false
                hint: "Public profile URL (without UTMs we add those)"
              - label: 'Twitch Url'
                name: twitch_url
                widget: string
                required: false
                hint: "Public profile URL (without UTMs we add those)"
              - label: 'YouTube Url'
                name: youtube_url
                widget: string
                required: false
                hint: "Public profile URL (without UTMs we add those)"
              - label: HIDDEN From Authors Page
                name: hidden
                widget: boolean
                default: false
                required: false
                hint: "Do you want to hide this author profile from the authors page"
      - label: 'Categories'
        name: categories
        file: 'content/categories.json'
        fields:
          - label: Categories
            name: categories
            identifier_field: slug
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
                hint: "Category name for the < Html /> tag style display i.e. 'Inspiration' or 'Tutorial'"
              - label: Plural
                name: plural
                widget: string
                hint: "Plural name for the homepage-sections and any breadcrumbs i.e. 'Ideas & Inspiration' or 'Tutorials'"
              - label: 'URL Slug'
                name: slug
                widget: string
                hint: "Slug for URLs like /categories/[slug] i.e. 'inspiration' or 'tutorial'"
              - label: 'Hex Color Code'
                name: color
                widget: string
                hint: "The html hex color code i.e. '#6544b8'"
