name: netlify-plugin-algolia-index

inputs:
  - name: generatedFunctionName
  - name: publishDirJSONFileName
  - name: exclude
  - name: tables
  - name: wordwrap
  - name: linkHrefBaseUrl
  - name: hideLinkHrefIfSameAsText
  - name: noLinkBrackets
  - name: ignoreHref
  - name: ignoreImage
  - name: preserveNewlines
  - name: decodeOptions
  - name: uppercaseHeadings
  - name: singleNewLineParagraphs
  - name: baseElement
  - name: returnDomByDefault
  - name: longWordSplit
  - name: format
  - name: unorderedListItemPrefix
  - name: debugMode