[build]
  command = "echo 'hello Netlify build'"
  publish = "fixtures/publishDir"
  functions = "fixtures/functions"

[[plugins]]
  package = "./fixtures/generator"
[[plugins]]
  package = "./index.js"
  [plugins.inputs]
    exclude = ["/search.html"]
    debugMode = true