name: Linting
on: [pull_request]

jobs:
  js-lint:
    name: JavaScript
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint Source Files
        run: npm run lint:js
        on:
          issues:
              types: [assigned]
          issue_comment:
              types: [created]
          pull_request:
              types: [closed]
  create_issue_branch_job:
      runs-on: ubuntu-latest
      steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
